JobBatchName    = calculate_histograms_$(STATION)_$(analyze_T1s)
Executable      = /cr/users/filip/Projects/SSDOnlineCalib/OfflineCalib/CalcHistos

error           = /cr/users/filip/Projects/SSDOnlineCalib/OfflineCalib/error.log

STATION         = NadiaEarlyFilteredDownsampled
DATE            = Mar2023
analyze_T1s     = 0

arguments       = "$(STATION) $(DATE) $(Process) $(analyze_T1s)"
request_memory  = 2G
max_idle        = 150
max_materialize = 20
                            
queue 800