#!/bin/bash

DOCSTRING1="%! TEX root = ../main.tex\n"
DOCSTRING2="% this file was automatically created"
DOCSTRING3="% via make by ../scripts/gather_appendices\n"

case $HOSTNAME in
    "beep-boop")
        TARGET=/home/quizznor/projects/phd-thesis/Thesis/app/appendix.tex
        ;;
    *"crcws"*)
        TARGET=/cr/users/filip/Thesis/app/appendix.tex
        ;;
esac

echo -e $DOCSTRING1 > $TARGET
echo -e $DOCSTRING2 >> $TARGET
echo -e $DOCSTRING3 >> $TARGET
ls app/*-*.tex | sed -e 's/\(.*\)/\\include{\1}/' >> $TARGET

