JobBatchName    = tot(d)_rate_calculation
Executable      = /cr/users/filip/Projects/totRateMaps/do_calculations.py
error           = /cr/users/filip/Projects/totRateMaps/do_calculations.err
#output          = /cr/users/filip/Projects/totRateMaps/do_calculations.out

should_transfer_files = YES
transfer_input_files = /cr/users/filip/bin/utils
arguments       = $(Process)
request_memory  = 2G
max_idle        = 150
# max_materialize = 20
                                                
queue 300