JobBatchName    = online_rates_#(STATION)_$(RATE)
Executable      = /cr/users/filip/Projects/SSDOnlineCalib/OnlineCalib/OnlineAlgorithm

output          = /cr/users/filip/Projects/SSDOnlineCalib/OnlineCalib/output.out
error           = /cr/users/filip/Projects/SSDOnlineCalib/OnlineCalib/error.err

STATION         = "Peru"
RATE            = "70"
GUESS           = "120"

arguments       = "$(STATION) $(RATE) $(GUESS)"
request_memory  = 1G
max_idle        = 150

queue 1
