JobBatchName    = online_rates_$(STATION)_$(RATE)
Executable      = /cr/users/filip/Projects/SSDOnlineCalib/OnlineCalib/OnlineAlgorithm

# output          = /cr/users/filip/Projects/SSDOnlineCalib/OnlineCalib/output.out
# error           = /cr/users/filip/Projects/SSDOnlineCalib/OnlineCalib/error.err

# target_rate   = 100 <-> 99   initial_guess
# target_rate   =  70 <-> 112  initial_guess

STATION         = RukaMalen
RATE            = 100
GUESS           = 99

arguments       = "$(STATION) $(RATE) $(GUESS)"
request_memory  = 1G
max_idle        = 150

queue 1
