JobBatchName    = get_T1s_$(DATE)_$(STATION)
Executable      = /cr/users/filip/Projects/SSDOnlineCalib/UUBCrosscheck/get_T1s.py

error           = /cr/users/filip/Projects/SSDOnlineCalib/UUBCrosscheck/error.log

STATION         = NuriaJr
DATE            = Nov2022

arguments       = "$(STATION) $(DATE) $(Process)"
request_memory  = 2G
max_idle        = 150
max_materialize = 20
                            
queue 400