JobBatchName    = ssd_tot(d)_rate_calculation_$(STATION)
Executable      = /cr/users/filip/Projects/SSDtotRateMaps/do_calculations_full_bandwidth.py
error           = /cr/tempdata01/filip/condor/SSDtotRateMaps/SSDtotRateMaps-$(Process).out
output          = /cr/tempdata01/filip/condor/SSDtotRateMaps/SSDtotRateMaps-$(Process).out

STATION         = Nadia

should_transfer_files = YES
transfer_input_files = /cr/users/filip/bin/utils
arguments       = "$(STATION) $(Process)"
request_memory  = 2G
max_idle        = 150
# max_materialize = 20
                                                
queue 11800