JobBatchName    = CALCULATE_MEAN_RATES
Executable      = /cr/users/filip/Projects/SSDOnlineCalib/CheckMonitHistos/calc_rates.py
error           = /cr/users/filip/Projects/SSDOnlineCalib/CheckMonitHistos/calc_rates.err
output          = /cr/users/filip/Projects/SSDOnlineCalib/CheckMonitHistos/calc_rates.out
log             = /cr/users/filip/Projects/SSDOnlineCalib/CheckMonitHistos/calc_rates.log

should_transfer_files = YES
transfer_input_files = workers.py

request_memory  = 2G                                                
queue 1