JobBatchName    = apply_downsampling_$(STATION)
Executable      = /cr/users/filip/Projects/SSDOnlineCalib/ExtractTraces/apply_downsampling.py

error           = /cr/users/filip/Projects/SSDOnlineCalib/ExtractTraces/error-apply_downsampling.log

STATION         = Svenja

arguments       = "$(STATION) $(Process)"
request_memory  = 2G
max_idle        = 150
max_materialize = 10
                                                
queue 800