JobBatchName    = extract_random_traces_$(STATION)
Executable      = /cr/users/filip/Projects/SSDOnlineCalib/ExtractTraces/extract_wcd_and_ssd.py

error           = /cr/users/filip/Projects/SSDOnlineCalib/ExtractTraces/condor-$(STATION).err

STATION         = Jaco

arguments       = "$(STATION) $(Process)"
request_memory  = 3G
max_idle        = 150
                                                
queue 800