JobBatchName    = extract_WCD_T1s_$(STATION)
Executable      = /cr/users/filip/Projects/SSDOnlineCalib/ExtractTraces/extract_wcd_T1s.py

error           = /cr/users/filip/Projects/SSDOnlineCalib/ExtractTraces/error-T1.log

STATION         = LeQuiDon

arguments       = "$(STATION) $(Process)"
request_memory  = 2G
max_idle        = 150
max_materialize = 10
                                                
queue 800