JobBatchName    = extract_random_traces_$(STATION)
Executable      = /cr/users/filip/Projects/SSDOnlineCalib/ExtractTraces/extract_wcd_and_ssd.py

error           = /cr/users/filip/Projects/SSDOnlineCalib/ExtractTraces/trace_extraction-$(DATE)-$(STATION).log

STATION         = NadiaEarly
DATE            = Mar2023

arguments       = "$(STATION) $(DATE) $(Process)"
request_memory  = 2G
max_idle        = 150
max_materialize = 20

                                          
queue 632