OnlineVEM: calculate_online_VEM.cxx
	g++ calculate_online_VEM.cxx -g -std=c++17 -o calculate_online_VEM
#		-fsanitize=address -fsanitize=undefined -fno-sanitize=null \
		-fno-sanitize-recover=all -fsanitize=float-divide-by-zero \
		-fsanitize=float-cast-overflow -fno-sanitize=alignment